import type { Bi } from "@/lib/i18n";

/**
 * ⚠ DRAFT LEGAL COPY — NOT REVIEWED BY COUNSEL.
 *
 * The client has not yet supplied Terms, Privacy or a refund policy. These
 * drafts exist so the pages are structurally complete, internally consistent
 * with what the rest of the site claims (15-day refund window, no password
 * storage, phone+OTP only, decision support not lending), and ready for a
 * lawyer to edit rather than write from scratch.
 *
 * Every page built from this file renders a visible "draft" banner. Remove the
 * banner only when the reviewed text replaces this content.
 */

export const legalUpdated = "2026-08-10";

export type LegalSection = { heading: Bi; body: Bi[] };

export const termsSections: LegalSection[] = [
  {
    heading: { en: "1. Who we are", bn: "১. আমরা কারা" },
    body: [
      {
        en: "This website is operated by DigiGram Ventures Ltd., a company registered in Bangladesh with its office at Level 4, 27 Shaptak Square, Dhanmondi, Dhaka-1205. References to \"we\", \"us\" and \"our\" mean DigiGram Ventures Ltd.",
        bn: "এই ওয়েবসাইট পরিচালনা করে ডিজিগ্রাম ভেঞ্চারস লিমিটেড, বাংলাদেশে নিবন্ধিত একটি কোম্পানি, যার কার্যালয় লেভেল ৪, ২৭ সপ্তক স্কয়ার, ধানমন্ডি, ঢাকা-১২০৫। \"আমরা\", \"আমাদের\" বলতে ডিজিগ্রাম ভেঞ্চারস লিমিটেডকে বোঝানো হয়েছে।",
      },
    ],
  },
  {
    heading: { en: "2. What this website is, and is not", bn: "২. এই ওয়েবসাইট কী, আর কী নয়" },
    body: [
      {
        en: "This website describes our projects and services and lets you express an interest in participating. It is not an offer of securities, not an invitation to invest under any regulated prospectus regime, and not financial advice. Nothing on this website should be read as a recommendation to invest.",
        bn: "এই ওয়েবসাইট আমাদের প্রকল্প ও সেবার বর্ণনা দেয় এবং অংশগ্রহণে আগ্রহ প্রকাশের সুযোগ দেয়। এটি সিকিউরিটিজের কোনো প্রস্তাব নয়, নিয়ন্ত্রিত প্রসপেক্টাসের অধীনে বিনিয়োগের আমন্ত্রণ নয়, আর্থিক পরামর্শও নয়। এখানকার কোনো কিছুই বিনিয়োগের সুপারিশ হিসেবে পড়া উচিত নয়।",
      },
      {
        en: "DigiGram Ventures Ltd. is not a licensed lender or deposit-taking institution. Where a bank, MFI or other licensed lender is involved in a project, that lender retains sole authority over credit approval, pricing, disbursement and recovery.",
        bn: "ডিজিগ্রাম ভেঞ্চারস লিমিটেড কোনো লাইসেন্সপ্রাপ্ত ঋণদাতা বা আমানত গ্রহণকারী প্রতিষ্ঠান নয়। কোনো প্রকল্পে ব্যাংক, এমএফআই বা অন্য লাইসেন্সপ্রাপ্ত ঋণদাতা যুক্ত থাকলে ঋণ অনুমোদন, মূল্য নির্ধারণ, বিতরণ ও আদায়ের একচ্ছত্র কর্তৃত্ব সেই ঋণদাতারই।",
      },
    ],
  },
  {
    heading: { en: "3. Returns and risk", bn: "৩. রিটার্ন ও ঝুঁকি" },
    body: [
      {
        en: "All returns shown on this website are estimated ranges based on a project's production plan and expected sale price. They are not guaranteed. Returns are generated by real agricultural production and are exposed to disease, mortality, weather, pest pressure, input-supply interruption and market price movement.",
        bn: "এই ওয়েবসাইটে দেখানো সব রিটার্ন প্রকল্পের উৎপাদন পরিকল্পনা ও প্রত্যাশিত বিক্রয়মূল্যের ভিত্তিতে প্রাক্কলিত পরিসর। এগুলো নিশ্চিত নয়। রিটার্ন তৈরি হয় বাস্তব কৃষি উৎপাদন থেকে এবং তা রোগ, মৃত্যু, আবহাওয়া, পোকার আক্রমণ, উপকরণ সরবরাহে বিঘ্ন ও বাজারদরের ওঠানামার ঝুঁকিতে থাকে।",
      },
      {
        en: "A cycle may return less than the stated range, and in a severe case some or all of the capital committed may be lost. Past project performance does not predict future results.",
        bn: "কোনো চক্র উল্লিখিত পরিসরের চেয়ে কম রিটার্ন দিতে পারে, আর গুরুতর ক্ষেত্রে প্রতিশ্রুত পুঁজির কিছু বা পুরোটাই হারাতে পারে। অতীতের প্রকল্প ফলাফল ভবিষ্যতের ইঙ্গিত দেয় না।",
      },
    ],
  },
  {
    heading: { en: "4. Accounts", bn: "৪. অ্যাকাউন্ট" },
    body: [
      {
        en: "Accounts are created with a mobile number and a one-time code sent by SMS. We do not create, store or ask for a password. You are responsible for keeping access to your mobile number secure and for telling us promptly if it is lost or transferred.",
        bn: "অ্যাকাউন্ট তৈরি হয় একটি মোবাইল নম্বর ও এসএমএসে পাঠানো এককালীন কোড দিয়ে। আমরা কোনো পাসওয়ার্ড তৈরি, সংরক্ষণ বা দাবি করি না। আপনার মোবাইল নম্বরে প্রবেশাধিকার নিরাপদ রাখা এবং তা হারিয়ে গেলে বা হস্তান্তরিত হলে দ্রুত আমাদের জানানো আপনার দায়িত্ব।",
      },
      {
        en: "Browsing this website does not require an account. Only the act of investing does.",
        bn: "এই ওয়েবসাইট দেখার জন্য অ্যাকাউন্ট লাগে না। কেবল বিনিয়োগের জন্যই লাগে।",
      },
    ],
  },
  {
    heading: { en: "5. Payments and refunds", bn: "৫. পরিশোধ ও ফেরত" },
    body: [
      {
        en: "Payment may be made by mobile financial service (bKash, Nagad), bank transfer, cheque collection or direct deposit. A booking is confirmed only when funds are received and reconciled.",
        bn: "পরিশোধ করা যায় মোবাইল আর্থিক সেবা (বিকাশ, নগদ), ব্যাংক ট্রান্সফার, চেক সংগ্রহ বা সরাসরি জমার মাধ্যমে। অর্থ গ্রহণ ও মিলকরণ সম্পন্ন হলেই কেবল বুকিং নিশ্চিত হয়।",
      },
      {
        en: "A refund may be requested within 15 days of the project start date. After that date the capital is committed to the production cycle and cannot be withdrawn before maturity.",
        bn: "প্রকল্প শুরুর তারিখ থেকে ১৫ দিনের মধ্যে অর্থ ফেরতের অনুরোধ করা যায়। এরপর পুঁজি উৎপাদন চক্রে প্রতিশ্রুত হয়ে যায় এবং মেয়াদপূর্তির আগে তোলা যায় না।",
      },
    ],
  },
  {
    heading: { en: "6. Content and intellectual property", bn: "৬. কনটেন্ট ও মেধাস্বত্ব" },
    body: [
      {
        en: "The DigiGram Ventures, Shathi, Shathi Sheba and Shadhin Cattle Feed names, logos and brand assets are our property. Website content may be quoted with attribution but not reproduced as a whole without written permission.",
        bn: "ডিজিগ্রাম ভেঞ্চারস, সাথী, সাথী সেবা ও স্বাধীন গো-খাদ্য নাম, লোগো ও ব্র্যান্ড অ্যাসেট আমাদের সম্পত্তি। ওয়েবসাইটের কনটেন্ট সূত্র উল্লেখ করে উদ্ধৃত করা যাবে, তবে লিখিত অনুমতি ছাড়া সম্পূর্ণ পুনরুৎপাদন করা যাবে না।",
      },
    ],
  },
  {
    heading: { en: "7. Governing law", bn: "৭. প্রযোজ্য আইন" },
    body: [
      {
        en: "These terms are governed by the laws of Bangladesh, and the courts of Dhaka have exclusive jurisdiction over any dispute arising from them.",
        bn: "এই শর্তাবলি বাংলাদেশের আইন দ্বারা পরিচালিত এবং এ থেকে উদ্ভূত যেকোনো বিরোধে ঢাকার আদালতের একচ্ছত্র এখতিয়ার থাকবে।",
      },
    ],
  },
];

export const privacySections: LegalSection[] = [
  {
    heading: { en: "1. What we collect", bn: "১. আমরা কী সংগ্রহ করি" },
    body: [
      {
        en: "When you create an account we collect your mobile number, and — if you choose to give them — your name, email address, district and stated interest (investor or Shathi partner). When you contact us we collect what you put in the form.",
        bn: "অ্যাকাউন্ট তৈরির সময় আমরা আপনার মোবাইল নম্বর সংগ্রহ করি, এবং আপনি দিতে চাইলে — নাম, ইমেইল ঠিকানা, জেলা ও উল্লিখিত আগ্রহ (বিনিয়োগকারী বা সাথী অংশীদার)। যোগাযোগ করলে ফর্মে আপনি যা লেখেন তা সংগ্রহ করি।",
      },
      {
        en: "We do not collect or store passwords. Identity documents are requested only where a specific project or partner lender requires them, and only at that point.",
        bn: "আমরা পাসওয়ার্ড সংগ্রহ বা সংরক্ষণ করি না। পরিচয়পত্র কেবল তখনই চাওয়া হয় যখন কোনো নির্দিষ্ট প্রকল্প বা অংশীদার ঋণদাতার প্রয়োজন হয় — এবং কেবল সেই পর্যায়েই।",
      },
    ],
  },
  {
    heading: { en: "2. Why we use it", bn: "২. কেন ব্যবহার করি" },
    body: [
      {
        en: "To verify who you are, to process and report on an investment, to answer an enquiry, and to meet our legal and record-keeping obligations. We do not sell personal data.",
        bn: "আপনার পরিচয় যাচাই করতে, বিনিয়োগ প্রক্রিয়া ও প্রতিবেদন তৈরি করতে, জিজ্ঞাসার উত্তর দিতে এবং আমাদের আইনি ও নথি সংরক্ষণের বাধ্যবাধকতা পূরণ করতে। আমরা ব্যক্তিগত তথ্য বিক্রি করি না।",
      },
    ],
  },
  {
    heading: { en: "3. Who we share it with", bn: "৩. কার সঙ্গে ভাগ করি" },
    body: [
      {
        en: "With a partner cooperative, lender or buyer only where it is necessary for a service you have asked for, and only with the scope you consented to. Consent is recorded with its date, channel, language and scope, and can be withdrawn.",
        bn: "কেবল আপনার চাওয়া কোনো সেবার জন্য প্রয়োজন হলে অংশীদার সমবায়, ঋণদাতা বা ক্রেতার সঙ্গে — এবং কেবল আপনি যে পরিধিতে সম্মতি দিয়েছেন সেই পরিধিতে। সম্মতি তারিখ, মাধ্যম, ভাষা ও পরিধিসহ নথিভুক্ত হয় এবং প্রত্যাহার করা যায়।",
      },
    ],
  },
  {
    heading: { en: "4. Your rights", bn: "৪. আপনার অধিকার" },
    body: [
      {
        en: "You can ask us what we hold about you, ask us to correct it, ask us to delete your account, and withdraw a consent you previously gave. Write to info@digigramventures.com or use the account-deletion page.",
        bn: "আপনার সম্পর্কে আমরা কী রাখি তা জানতে চাইতে পারেন, সংশোধনের অনুরোধ করতে পারেন, অ্যাকাউন্ট মুছে ফেলতে বলতে পারেন এবং আগে দেওয়া সম্মতি প্রত্যাহার করতে পারেন। info@digigramventures.com ঠিকানায় লিখুন বা অ্যাকাউন্ট মুছে ফেলার পাতাটি ব্যবহার করুন।",
      },
    ],
  },
  {
    heading: { en: "5. Cookies and analytics", bn: "৫. কুকি ও অ্যানালিটিক্স" },
    body: [
      {
        en: "We store your language choice in a cookie so the site opens in the language you last used. Any analytics we add will be listed here with its purpose before it is switched on.",
        bn: "আপনার ভাষা পছন্দ একটি কুকিতে সংরক্ষণ করি, যাতে সাইটটি আপনার সর্বশেষ ব্যবহৃত ভাষায় খোলে। ভবিষ্যতে কোনো অ্যানালিটিক্স যুক্ত করলে চালু করার আগে তার উদ্দেশ্যসহ এখানে উল্লেখ করা হবে।",
      },
    ],
  },
];
